DATALOADER:
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 288
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 288

OPTIM:
  NAME: 'sgd'
  LR: 0.05
  STEPSIZE: [30]
  MAX_EPOCH: 30
  LR_SCHEDULER: 'cosine'

TEST:
  EVALUATOR: 'Regression' 

TRAINER:
  DAEL:
    STRONG_TRANSFORMS: ['randaugment2', 'normalize']