DATALOADER:
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 288
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 288
DATASET:
   SOURCE_DOMAINS:
      - base_small
      - colors
      - colors2
      - blurred
      - blurred2
      - shapes
      - shapes2
      - textures
      - textures2
OPTIM:
  NAME: 'sgd'
  LR: 0.05
  STEPSIZE: [30]
  MAX_EPOCH: 30
  LR_SCHEDULER: 'cosine'

TEST:
  EVALUATOR: 'Regression' 

TRAINER:
  DAEL:
    STRONG_TRANSFORMS: ['randaugment2', 'normalize']