from .mcd import MCD
from .mme import MME
from .adda import ADDA
from .dael import DAEL
from .dann import DANN
from .adabn import AdaBN
from .m3sda import M3SDA
from .source_only import SourceOnly
from .self_ensembling import SelfEnsembling
from .dael_regression import DAELReg
#from .dael_gated import DAELGated
from .alt_dael_gated import AltDAELGated
